### PR TITLE
Delete unneeded comment (xray-rails) in Gemfile

### PR DESCRIPTION
**Pull request by gazayas**
I'm assuming we don't need these lines anymore since we merged in [nice_partials#28](https://github.com/bullet-train-co/nice_partials/pull/28)

Thanks @kaspth!

### CODE REVIEW

**Comment by kaspth** [comment]
Don't think we can do this yet, it looks like the compatibility fix PR is still open on xray-rails https://github.com/brentd/xray-rails/pull/108

**Comment by gazayas** [comment]
Okay, I guess I'm just confused as to why it's commented out. Are we leaving it just in case developers want to use xray?

**Comment by andrewculver** [comment]
@gazayas Ah, yes, this is safe to remove because we got rid of X-ray as a dependency! We just use the regular Rails annotations now!

**Comment by gazayas** [comment]
@andrewculver Thanks for clarifying 🙌

**Pull request merged**
