### PR TITLE
Super Scaffold color picker with default colors

### PR DESCRIPTION
**Pull request by gazayas**
・Closes [this issue](https://github.com/bullet-train-co/bullet_train-super_scaffolding/issues/13)

[Joint PR](https://github.com/bullet-train-co/bullet_train-super_scaffolding/pull/20)

To run the tests, add the following to the Gemfile before running the system test setup script:
```ruby
gem "bullet_train-super_scaffolding", git: "git@github.com:bullet-train-co/bullet_train-super_scaffolding.git", branch: "fixes/show-default-colors"
```

### CODE REVIEW

**Comment by andrewculver** [comment]
@gazayas Can you rebase this? 🙏

**Comment by gazayas** [comment]
@andrewculver
I added a couple of more PRs, so if we add these two, this PR should be good to go!
[bullet_train-super_scaffolding#37](https://github.com/bullet-train-co/bullet_train-super_scaffolding/pull/37)
[bullet_train-themes-tailwind_css#5](https://github.com/bullet-train-co/bullet_train-themes-tailwind_css/pull/5)

## Testing
1. Substitute the Super Scaffolding gem for the branch from PR 37:
```ruby
gem "bullet_train-super_scaffolding", git: "git@github.com:bullet-train-co/bullet_train-super_scaffolding.git", branch: "fixes/scaffold-color-picker-options"
```
2. Add the Tailwind CSS branch:
```ruby
gem "bullet_train-themes-tailwind_css", git: "git@github.com:bullet-train-co/bullet_train-themes-tailwind_css.git", branch: "fixes/use-hash-for-options"
```
3. `bundle add spring`

4. Run the set up script and then the test:
```
bundle exec test/bin/setup-super-scaffolding-system-test && \
test/system/super_scaffolding_partial_test.rb
```

**Comment by andrewculver** [comment]
@gazayas A wild conflict has appeared!

**Comment by gazayas** [comment]
@andrewculver
*@gazayas used swift!*

I checked this locally just to make sure everything was working, and unfortunately `password_field` isn't being scaffolded correctly for some reason, so I think I'll address it in another PR so things don't get complicated. I'll adjust the tests here again if I can get it to work.

**Pull request merged**
