### PR TITLE
Memberships API

### PR DESCRIPTION
**Pull request by newstler**
That implements memberships API, adds OpenAPI specs, and fixes path examples generation.
Required by https://github.com/bullet-train-co/bullet_train-core/pull/237

### CODE REVIEW

**Comment by jagthedrummer** [comment]
Hey @newstler, is this still something that you'd like to see merged. If so, would you mind rebasing/merging `main` and making sure that tests are passing?

**Comment by newstler** [comment]
Hey @jagthedrummer, sure! Take also a look at #749 (and https://github.com/bullet-train-co/bullet_train-core/pull/270) please! Very much awaited!

**Comment by newstler** [comment]
Updated! I still don't know how to run tests here against a specific branch in a core repo, that's why tests are falling.

**Comment by jagthedrummer** [comment]
Hey @newstler, the `Core:` tests in Circle will automatically run against a matching branch in the core repo if it can find one. Since your branches are named `features/api-memberships` in both repos we're running those tests against your changes in `core`. The ones that are failing here are are the `Release:` tests, which we purposefully run against the currently-released versions of the gems.

This helps us know when we're introducing a breaking change into the starter repo because of dependencies on new versions of the gems. These failures basically mean that we need to merge the changes in `core`, then release new versions of the gems, then merge this PR, and then cut a new release of the starter repo.

**Pull request merged**
