### PR TITLE
Implement home page

### PR DESCRIPTION
**Pull request by gazayas**
Closes [#615.](https://github.com/bullet-train-co/bullet_train-core/issues/615)

To view the page:
1. Comment out `include RootRedirect` in the [home controller](https://github.com/bullet-train-co/bullet_train/blob/main/app/controllers/public/home_controller.rb).
2. Add an `index` action in the same controller.

Joint PR
- https://github.com/bullet-train-co/bullet_train-core/pull/628

https://github.com/bullet-train-co/bullet_train/assets/10546292/3bb3240a-0627-42c8-be12-899a8eb7ff05

### CODE REVIEW

**Comment by gazayas** [comment]
We already had `stimulus-reveal`, so I thought adding `stimulus-scroll-reveal` from [Stimulus Components](https://www.stimulus-components.com/).

@pascallaliberte There's some CSS stuff going on here, so I thought I'd tag you for a review.

**Comment by gazayas** [comment]
Also, I didn't include my `yarn.lock` here because it's giving me a massive diff, and I'm still not quite sure how to compensate for it.

**Comment by jagthedrummer** [comment]
> Also, I didn't include my `yarn.lock` here because it's giving me a massive diff, and I'm still not quite sure how to compensate for it.

@gazayas I just pulled this branch and did a `yarn install` and this is the only change that it's trying to make to `yarn.lock`:

```diff
+stimulus-scroll-reveal@^3.2.0:
+  version "3.2.0"
+  resolved "https://registry.yarnpkg.com/stimulus-scroll-reveal/-/stimulus-scroll-reveal-3.2.0.tgz#e9bdf2c0ddce82c24df99ba627f2f3375bc64f41"
+  integrity sha512-KxXHibsGVqvBJ4TqUaTwss36WX543dlUWoNbDXvkAfuddE6H/D7egkVF9v85LEtCVd2h9KkrTNykBnPqyxpAoQ==
+
```

I wonder if it's a yarn version issue. What version are you running? I'm on `1.22.19`.

**Comment by jagthedrummer** [comment]
Just played around with this and it looks great!

My only teeny tiny concern is whether we want to introduce a new dependency on `stimulus-scroll-reveal` for content that we expect people to replace.

Not a huge concern for me, and this is not a request to remove it. More of a comment in passing to see if anyone else thinks it's a concern.

**Comment by gazayas** [comment]
> Just played around with this and it looks great!

Thank you!

> My only teeny tiny concern is whether we want to introduce a new dependency on stimulus-scroll-reveal for content that we expect people to replace.

Totally valid. I debated whether to put it in or not, but...I really like the reveal animation 😩😂

Granted, the vanilla Rails home page doesn't have any fancy scroll reveal stuff going on, so I can also see why we wouldn't need it 🤷‍♂️ I'm down either way.

**Comment by gazayas** [comment]
> I wonder if it's a yarn version issue. What version are you running? I'm on 1.22.19.

Yup, you were right. I've been running on 3.6.1 for a while. Just pushed the diff with 1.22.19.

**Comment by gazayas** [comment]
@pascallaliberte Thank you 🙂

**Review by jagthedrummer — APPROVED** [review]

**Pull request merged**
