### PR TITLE
Fix targets-many Action Model test

### PR DESCRIPTION
**Pull request by gazayas**
Depends on https://github.com/bullet-train-pro/bullet_train-action_models/pull/67

I also noticed the `targets-one` test is failing too, so I want to look into again after CableReady v5.0.0 is merged in.

### CODE REVIEW

**Comment by gazayas** [comment]
I went ahead merged main on this one and confirmed that the targets-many test is working locally.

**Review by jagthedrummer — APPROVED** [review]
@gazayas This looks good to me! But I don't know a lot about the BT Action Models stuff, so I just wanted to confirm that you're still good with it before I merge.

**Comment by gazayas** [comment]
@jagthedrummer I actually might have to sit down with this one for a bit, we're getting a locale error when trying to register a new account and I'm not sure where it's coming from:

Screenshot from 2023-08-04 15-50-22

**Comment by gazayas** [comment]
It looks like this is happening against the main branch when trying to run Action Model system tests.

**Comment by gazayas** [comment]
@jagthedrummer Figured it out, it was definitely related to https://github.com/bullet-train-pro/bullet_train-action_models/issues/79 which has a fix in the works:
- https://github.com/bullet-train-pro/bullet_train-action_models/pull/80

I made a couple of other tweaks, so this one should be good to go.

**Comment by gazayas** [comment]
> @gazayas, just to make sure I'm understanding correctly, are you saying that this PR is dependent on [bullet-train-pro/bullet_train-action_models#80](https://github.com/bullet-train-pro/bullet_train-action_models/pull/80)?

It's not dependent on bullet-train-pro/bullet_train-action_models#80 per se, but the Action Model system tests we have in place in the starter repository are, and they currently fail without that fix. I isolated the tests here for targets-many so it should be fine for merging, bullet-train-pro/bullet_train-action_models#80 is just another PR I think we should prioritize before merging the other Action Model PRs to make sure all of our tests are ok.

**Comment by jagthedrummer** [comment]
Thanks for the work on this one @gazayas! I ended up pulling most of these changes into #892 which is a joint PR with https://github.com/bullet-train-pro/bullet_train-action_models/pull/80. Tests are passing in both repos for those PRs/branches, so I'm going to merge them and then close this one.

**Comment by gazayas** [comment]
> Thanks for the work on this one @gazayas! I ended up pulling most of these changes into #892 which is a joint PR with [bullet-train-pro/bullet_train-action_models#80](https://github.com/bullet-train-pro/bullet_train-action_models/pull/80). Tests are passing in both repos for those PRs/branches, so I'm going to merge them and then close this one.

@jagthedrummer Sounds good!

**Pull request closed without merging**
