### PR TITLE
Bundle capybara-lockstep to improve System Test stability.

### PR DESCRIPTION
**Pull request by kaspth**
https://github.com/makandra/capybara-lockstep

Seems like it costs 5 seconds, but the build fails in strange ways. So I'm opening this for posterity.

I also used `bundle open bullet_train-themes-light` to add the expected JS include in `app/views/themes/light/layouts/_head.html.erb`:

```diff
+<%= capybara_lockstep if defined?(Capybara::Lockstep) %>
<%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
```

@gazayas @jagthedrummer I'll probably close this unless either of you feel like diving into the test failures, because I don't know what they mean 😊

### CODE REVIEW

**Comment by jagthedrummer** [comment]
Oh, this looks interesting. I didn't know about `capybara-lockstep`. I actually think the test failure on this PR is a timing issue that might be addressed by `capybara-lockstep` if it weren't commented out of the `Gemfile`.

**Comment by gazayas** [comment]
I like the idea of including this because I've run into many `visit`-related test failures in the past, and it would be nice not to have to think about them. I'll try to keep this in mind so I can look into the test failures soon.

**Comment by jagthedrummer** [comment]
@kaspth I un-commented the gem in the `Gemfile` to activate it, and added the required JS snippet to `app/views/layouts/_head.html.erb` and verified that the integration is working by briefly un-commenting the debug line in `test/application_system_test_case.rb`. It seems to be doing the thing. I've re-run tests on this PR a number of times and none of the occasionally-flaky tests flaked out, so... maybe this does the trick? 🤞

I think it's worth merging and giving it a shot. Is there anything else you think we should do on this?

**Comment by kaspth** [comment]
> I think it's worth merging and giving it a shot. Is there anything else you think we should do on this?

@jagthedrummer sounds good, let's give it a shot 😄

**Pull request merged**
