### PR TITLE
Example - Get rspec working

### PR DESCRIPTION
**Pull request by jagthedrummer**
DO NOT MERGE

This is just to illustrate what I did to get rspec working. We don't want to ship rspec pre-configured, but we do want it to be easy (and possible!) to get running.

This commit finally got it to work: https://github.com/bullet-train-co/bullet_train/commit/1aa6ef256892acf639f84329a8e85f66f721bf2d

I'll open a PR to get that commit merged to `main` so that it's easy for other people to get rspec running.

### CODE REVIEW

**Comment by seanders** [comment]
I'll try to dig some more digging, but I'm seeing an issue running the specs still. 
image

**Comment by gazayas** [comment]
Just here to say that the branch is working for me.


image

**Comment by seanders** [comment]
@gazayas Any chance you're able to get a request spec to run too?

**Comment by gazayas** [comment]
@seanders A very simple one, but yes. I'm curious as to why the Cloudinary constant isn't loading for you :thinking:

image

**Pull request closed without merging**
