### PR TITLE
Enable password field tests, move Super Scaffolding file tests

### PR DESCRIPTION
**Pull request by gazayas**
Addresses a couple of TODOs in the Super Scaffolding test setup script.

As far as `TestFile` goes, we already had a test for it in the partial test, but we can go with this PR if it belongs in `super_scaffolding_test.rb` instead.

### CODE REVIEW

**Comment by andrewculver** [comment]
@gazayas <a href="https://imgflip.com/i/7jz0wz"></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>

**Comment by gazayas** [comment]
Meme saved! 👆

Hadn't checked my fork in a while, 22 commits behind will do it 😅️
22 commits behind

**Comment by jagthedrummer** [comment]
@gazayas Looks like another conflict has cropped up. If you can resolve it I'll merge this ASAP to avoid any more conflicts.

**Comment by gazayas** [comment]
It looks like some of these tests were covered in #86 and #660, so there's not much left here after merging. We do get rid of the TODOs though, and add we also add one TODO related to finding a "one" option with Capybara. This one should be good to go!

**Pull request merged**
