### PR TITLE
Add option to pass custom date and time formats

### PR DESCRIPTION
**Pull request by gazayas**
This gives developers the option to pass a custom format to `Date` and `DateTime` partials.
Context: https://discord.com/channels/836637622432170028/836637623048601633/973728513217675354

Given a model named `PartialTest` with a `Date` attribute named `date_test`, we can write the following:
```erb
<td><%= render 'shared/attributes/date', attribute: :date_test, url: [:account, partial_test], date_format: "%m/%d" %></td>
<td><%= render 'shared/attributes/date_and_time', attribute: :created_at, date_format: "%m/%d", time_format: "%I %p" %></td>
```
This gives developers the freedom to write their own formats if they want to.

## Setup
I'm having a problem with the test because Capybara isn't picking up on the changes made when overwriting the file. I'm not quite sure how to handle this one, but I thought it would be better to push some tests rather than none.

Also, we need the `chronic` gem which is to be pulled in via [this PR](https://github.com/bullet-train-co/bullet_train/pull/49/files). Before that gets merged in, you can check the logic by replacing the appropriate Bullet Train packages in the Gemfile, along with simply adding Chronic:
```ruby
gem "chronic"
gem "bullet_train", git: "git@github.com:gazayas/bullet_train.git", branch: "features/custom-date-formats"
gem "bullet_train-themes", git: "git@github.com:bullet-train-co/bullet_train-themes.git", branch: "features/custom-date-formats"
```

### CODE REVIEW

**Comment by gazayas** [comment]
[Joint PR](https://github.com/bullet-train-co/bullet_train-base/pull/44) ← Bullet Train Base
[Joint PR](https://github.com/bullet-train-co/bullet_train-themes/pull/6) ← Bullet Train Themes

**Comment by jagthedrummer** [comment]
@gazayas This looks good to me, and since the dependent PRs are already merged it seems like it should be good to go. Except for the fact that there's a merge conflict. If we can get the conflict sorted out I think we should merge this.

**Comment by gazayas** [comment]
@jagthedrummer I ended up removing the tests for the custom formats because Capybara wasn't picking up on the edited page. I originally was working with `_index/html.erb` but changed it to `show.html.erb`. Here's how I edited the file:

```ruby
transformed_content = original_content.map do |line|
  if line.match?(/attribute: :date_test/)
    line.gsub(/ %>/, ", date_format: #{custom_date_format} %>")
  elsif line.match?(/attribute: :date_time_test/)
    line.gsub(/ %>/, ", date_format: #{custom_date_format}, time_format: #{custom_time_format} %>")
  else
    line
  end
end
```

After editing the file, running `refresh` to refresh the session and then visiting the show page, the changes weren't present in the test although it was working fine in the browser.

What I can do is write about the change in the docs, we just won't have tests for now.

**Comment by gazayas** [comment]
Now we just have 0 changes though, also because we added `PartialTest` to the tests after I opened this PR... I'll write up some documentation and link it here, then close it.

**Comment by gazayas** [comment]
Just opened https://github.com/bullet-train-co/bullet_train-core/pull/364, will go ahead and close this one.

**Pull request closed without merging**
