### PR TITLE
Add Address model, Factory, Addresses::Country and Addresses::Region

### LINKED ISSUE #631: Add an address multi-field partial
Create an address field that:
* includes all fields for an address: country, postal code, address lines 1 and 2, city, region (state, province, prefecture, etc)
* has the region and postal code field update themselves depending on the country selected
* is stored in a separate table, using `has_one :billing_address, as: :addressable` or something similar allowing for multiple such polymorphic fields per model

### PR DESCRIPTION
**Pull request by pascallaliberte**
Closes #631 

Joint PR:
- https://github.com/bullet-train-co/bullet_train-core/pull/86

To Do:
- [X] Add Address model
- [X] Add Addresses Factory
- [X] Add Addresses::Country
- [X] Add Addresses::Region
- [x] Update tangible_thing test for address field country_id dependent fields

### CODE REVIEW

**Comment by olbrich** [comment]
This looks really nice. FYI, I already have an 'Address' model in my own app, seems like this might conflict with it in a few places. Any way to make it optional?

**Comment by pascallaliberte** [comment]
> This looks really nice. FYI, I already have an 'Address' model in my own app, seems like this might conflict with it in a few places. Any way to make it optional?

Once you pull from the main branch, this line will be merged into your `app/models/address.rb`. You can just remove it locally.

https://github.com/bullet-train-co/bullet_train/blob/490d472e6f40d21fe26e4197bd130c26fdff6ed3/app/models/address.rb#L4

Same with the `extend` line on line 2:

https://github.com/bullet-train-co/bullet_train/blob/490d472e6f40d21fe26e4197bd130c26fdff6ed3/app/models/address.rb#L1-L5

**Comment by jagthedrummer** [comment]
@pascallaliberte, what's the status on this? Is this still something that you'd like to see merged?

**Comment by pascallaliberte** [comment]
@jagthedrummer 

> @pascallaliberte, what's the status on this? Is this still something that you'd like to see merged?

I'll do a check next week on the joint PRs to button things up again and let you know.

**Comment by pascallaliberte** [comment]
@jagthedrummer it seems it's just the Release tests that don't pass because `use-core-repo` is set to `false`. Assuming this is expected behaviour?

Otherwise, it's ready to merge.

The associated PR https://github.com/bullet-train-co/bullet_train-core/pull/86 is ready to go as well: merge and release js packages.

**Comment by jagthedrummer** [comment]
@pascallaliberte, yes, I would expect tests to fail in the `Release:` jobs since this PR requires the new functionality that you added in the joint PR in `core`. The failures help us know when we need to release a new version of `core` in order to accommodate changes in the starter repo.

**Comment by jagthedrummer** [comment]
@pascallaliberte, I just pulled this down and played with it and it's super cool! Great work!

There's now a merge conflict on the joint PR over in `core`. But once that's resolved I think this is ready for merging.

**Comment by jagthedrummer** [comment]
Just wanting to capture some stuff that I thought of that we'll want to do soon that relate to these PRs. Most of these are probably best handled in some follow-on PRs.

* What's going to be someone's experience if they already have an `Address` model in their app with an `addresses` table? Where should we document our advice about how to handle this situation? (This one might be a blocker on merging and releasing this.)
* Document the new `address_field` partial in the Field Partials doc
* Add docs for the new no-config mechanism for allowing form fields to fetch themselves new options and labels
* Document the new Stimulus controllers for dependent fields
* Is there anything that has to be done to make this available to Super Scaffolding?
* Document how to take advantage of this during Super Scaffolding

**Comment by pascallaliberte** [comment]
@jagthedrummer I had as a follow-up task to address the super-scaffolding of this type of field.

The `addresses` table conflict is indeed super likely.

I think we'll keep the migration in and, as everything in the starter repo, lean on people picking and choosing what they keep from upgrades from upstream, as recommended in the [upgrades doc](https://bullettrain.co/docs/upgrades#4-merge-in-the-newest-stuff-from-bullet-train-and-resolve-any-merge-conflicts).

For docs, I can take it on in a separate PR. The new pattern for self-updating fields is indeed a new approach that deserves a bit of spotlight.

But maybe a bit more should be bundled in with this feature before release. Initially it was "let's just ship this", but maybe we're at a point where wrapping a feature like this with docs is required. Up to you.

**Comment by jagthedrummer** [comment]
@pascallaliberte, I'm totally fine with merging this as is to avoid more merge conflicts, and then following up with the docs. Sound good to you?

**Pull request merged**
